import "./globals.css";
import type {Metadata} from "next";
import Footer from "@/components/Footer";
import {Providers} from "../components/Providers";
import Navbar from "@/components/Navbar"
import {Box, CssBaseline} from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps =
  {
    children: React.ReactNode;
  }


export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
    <body style={{overflowX: 'hidden'}}>
    <Providers>
      <CssBaseline/>
      <Navbar/>
      <Box
        component="main"
        minHeight={`calc(100dvh - 355px)`}
      >
        {children}
      </Box>
      <Footer/>
    </Providers>
    </body>
    </html>
  );
}
