import "./globals.css";
import type {Metadata} from "next";
import Footer from "@/components/Footer";
import {Providers} from "../components/Providers";
import Navbar from "@/components/Navbar"
import {CssBaseline} from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  }) {

  return (
    <html lang="en">
      <body>
        <Providers>
          <CssBaseline />
            <Navbar/>
            {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
